In [1]:
import numpy as np
import qutip as qt

In [23]:
psi = qt.tensor(qt.basis(2, 0), qt.basis(2, 1)) + qt.tensor(qt.basis(2, 1), qt.basis(2, 0))
print(psi)
print('rho_A')
print(psi.ptrace(0))
print('rho_B')
print(psi.ptrace(1))

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [1.]
 [0.]]
rho_A
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]
rho_B
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]


In [11]:
dm = qt.rand_dm_hs(8, dims=[[2] * 3] * 2)
dm

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 5.24357349e-02+4.43327300e-19j -3.01910471e-02-2.84712348e-02j
   1.87209727e-02-1.09008104e-02j  1.58473586e-04-1.83508461e-03j
  -1.38711740e-03+6.61924429e-03j  2.44841395e-02-7.04507829e-03j
   1.37184072e-02-1.29662172e-02j -2.35991103e-02+1.75867378e-02j]
 [-3.01910471e-02+2.84712348e-02j  1.44621451e-01+7.31414359e-20j
  -4.06914692e-03+8.56668752e-02j  3.35710823e-02+1.55171427e-02j
  -2.47283550e-02-1.52707456e-02j -5.63471045e-02+2.92482851e-02j
   4.21737916e-02+2.29108413e-02j  4.42691947e-02-4.06523507e-02j]
 [ 1.87209727e-02+1.09008104e-02j -4.06914692e-03-8.56668752e-02j
   1.81777024e-01-1.60433100e-18j -1.43187543e-02+2.12275105e-02j
  -1.78416640e-02+6.81269732e-02j  1.21481844e-02+4.50465598e-02j
  -4.82892219e-02-3.88139922e-02j  7.57357486e-03-4.77885220e-02j]
 [ 1.58473586e-04+1.83508461e-03j  3.35710823e-02-1.55171427e-02j
  -1.43187543e-02-2.12275105e-02j  1.

In [50]:
phi = np.array([0, 1, 1, 0])
print(type(phi))
rho = np.einsum('i,j->ij', phi, phi.conj())
print(rho)
rho.reshape(2, 2, 2, 2)
reduced_rho_B = np.einsum('ijik->jk', rho.reshape(2, 2, 2, 2)) # Tr_A
reduced_rho_A = np.einsum('ijkj->ik', rho.reshape(2, 2, 2, 2)) # Tr_B
print(reduced_rho_A)
print(reduced_rho_B)

<class 'numpy.ndarray'>
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]


In [52]:
phi0 = np.array([0, 1, 1, 0])
phi1 = np.array([1, 0])
phi = np.einsum('i,I->iI', phi0, phi1.conj()).reshape(8)
print(phi)
rho = np.einsum('i,j->ij', phi, phi.conj())
rho = rho.reshape(4, 2, 4, 2)
reduced_rho_B = np.einsum('ijiJ->jJ', rho) # Tr_A
reduced_rho_A = np.einsum('ijkj->ik', rho) # Tr_B
print(reduced_rho_A)  # Tr_B
print(reduced_rho_B)  # Tr_A

[0 0 1 0 1 0 0 0]
[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
[[2 0]
 [0 0]]


In [44]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.einsum('i,j->ij', a, b))
print(np.einsum('i,j->ij', a, b).flatten())
print(np.einsum('i,j->ij', a, b).reshape(4))
print(np.einsum('i,j->ij', a, b).reshape(4, 1))

[[3 4]
 [6 8]]
[3 4 6 8]
[3 4 6 8]
[[3]
 [4]
 [6]
 [8]]
